version: '3'

services:
  mybot:
    image: tutugarin/telegram_bot
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
    environment:
      TELEGRAM_BOT_TOKEN: "${BOT_TOKEN}" #  <--- значение будет взято из переменной окружения, определенной на момент запуска docker-compose up

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --scope myscope
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"